# Generated by Django 4.2.5 on 2023-10-02 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('empno', models.IntegerField(primary_key=True, serialize=False)),
                ('empname', models.CharField(max_length=20)),
                ('salary', models.IntegerField()),
                ('doj', models.DateField(auto_now=True)),
                ('gender', models.CharField(max_length=1)),
            ],
        ),
    ]
