# Generated by Django 4.2.5 on 2023-09-28 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORMApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='id',
        ),
        migrations.AlterField(
            model_name='employee',
            name='empno',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
