# Generated by Django 4.2.5 on 2023-09-29 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORMApp', '0002_remove_employee_id_alter_employee_empno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deportment',
            fields=[
                ('dptno', models.IntegerField(primary_key=True, serialize=False)),
                ('dptname', models.CharField(max_length=20)),
            ],
        ),
    ]
