# Generated by Django 4.2.5 on 2023-09-29 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ORMApp', '0003_deportment'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='deportment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ORMApp.deportment'),
        ),
    ]
