# Generated by Django 4.2.5 on 2023-09-29 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ORMApp', '0004_employee_deportment'),
    ]

    operations = [
        migrations.CreateModel(
            name='person',
            fields=[
                ('pno', models.IntegerField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=20)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Aadhar',
            fields=[
                ('ano', models.IntegerField(primary_key=True, serialize=False)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ORMApp.person')),
            ],
        ),
    ]
