# Generated by Django 4.2.5 on 2023-09-30 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORMApp', '0005_person_aadhar'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('sid', models.IntegerField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=20)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='course',
            fields=[
                ('cid', models.IntegerField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=20)),
                ('students', models.ManyToManyField(to='ORMApp.student')),
            ],
        ),
    ]
