# Generated by Django 4.2.5 on 2023-10-01 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ORMApp', '0007_child1_child2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Base2',
            fields=[
                ('empno', models.IntegerField(primary_key=True, serialize=False)),
                ('empname', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('base2_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ORMApp.base2')),
                ('salary', models.IntegerField()),
            ],
            bases=('ORMApp.base2',),
        ),
    ]
