# Generated by Django 4.2.5 on 2023-10-01 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ORMApp', '0008_base2_child'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProxy',
            fields=[
                ('employee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ORMApp.employee')),
            ],
            bases=('ORMApp.employee',),
        ),
    ]
