# Generated by Django 4.2.5 on 2023-10-02 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('pimage', models.ImageField(upload_to='image/')),
            ],
        ),
    ]
